/**
 * Shared type for campaign suggestions generated by signal scanners.
 * Used by both the API route and the frontend modal.
 */
export interface CampaignSuggestion {
  signal_type: 'weather' | 'repurchase' | 'inventory' | 'local_event' | 'history';
  title: string;
  description: string;
  urgency: 'low' | 'medium' | 'high';
  suggested_name: string;
  suggested_festival: string;
  suggested_message: string;
  suggested_scheduled_at: string;
  /** Pre-computed deterministic tag for this campaign, e.g. "weather_sg" or "repurchase_2026_6" */
  suggested_tag: string;
  metadata: Record<string, unknown>;
}
